# alt_send_esc = true
#background_opacity = 0.85
#enable_experimental_conpty_backend = false
general.live_config_reload = true
working_directory = "None"

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x657b83"
blue = "0x268bd2"
cyan = "0x2aa198"
green = "0x859900"
magenta = "0x6c71c4"
red = "0xdc322f"
white = "0x93a1a1"
yellow = "0xb58900"

[colors.cursor]
cursor = "0x93a1a1"
text = "0x002b36"

[colors.normal]
black = "0x002b36"
blue = "0x268bd2"
cyan = "0x2aa198"
green = "0x859900"
magenta = "0x6c71c4"
red = "0xdc322f"
white = "0x93a1a1"
yellow = "0xb58900"

[colors.primary]
background = "0x002b36"
foreground = "0x93a1a1"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
# ref_test = false
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 13.0

#[font."<<"]
#size = 12.0
#use_thin_strokes = true

#[font."<<".glyph_offset]
#x = 0
#y = 0
#
#[font."<<".offset]
#x = 0
#y = 0

[font.normal]
family = "FiraCode Nerd Font"
style = "Light"

[font.offset]
y = 3

# [fonts.base]
# size = 12.0
# use_thin_strokes = true
# 
# [fonts.base.glyph_offset]
# x = 0
# y = 0
# 
# [fonts.base.offset]
# x = 0
# y = 0
# 
# [fonts.consolas]
# size = 13.0

# [fonts.consolas."<<"]
# size = 12.0
# use_thin_strokes = true
# 
# [fonts.consolas."<<".glyph_offset]
# x = 0
# y = 0
# 
# [fonts.consolas."<<".offset]
# x = 0
# y = 0

# [fonts.consolas.normal]
# family = "Consolas for Powerline"
# 
# [fonts.fira-code]
# size = 12.0

#[fonts.fira-code."<<"]
#size = 12.0
#use_thin_strokes = true
#
#[fonts.fira-code."<<".glyph_offset]
#x = 0
#y = 0
#
#[fonts.fira-code."<<".offset]
#x = 0
#y = 0

# [fonts.fira-code.normal]
# family = "Fira Code Light"
# 
# [fonts.fira-nerd]
# size = 13.0

# [fonts.fira-nerd."<<"]
# size = 12.0
# use_thin_strokes = true
# 
# [fonts.fira-nerd."<<".glyph_offset]
# x = 0
# y = 0
# 
# [fonts.fira-nerd."<<".offset]
# x = 0
# y = 0

# [fonts.fira-nerd.normal]
# family = "FiraCode Nerd Font"
# style = "Light"
# 
# [fonts.fira-nerd.offset]
# y = 3
# 
# [fonts.hack]
# size = 12.0

# [fonts.hack."<<"]
# size = 12.0
# use_thin_strokes = true
# 
# [fonts.hack."<<".glyph_offset]
# x = 0
# y = 0
# 
# [fonts.hack."<<".offset]
# x = 0
# y = 0

# [fonts.hack.normal]
# family = "Hack Nerd Font"
# style = "Regular"
# 
# [fonts.hack.offset]
# y = 5
# 
# [fonts.inconsolata]
# size = 12.0

# [fonts.inconsolata."<<"]
# size = 12.0
# use_thin_strokes = true
# 
# [fonts.inconsolata."<<".glyph_offset]
# x = 0
# y = 0
# 
# [fonts.inconsolata."<<".offset]
# x = 0
# y = 0

# [fonts.inconsolata.normal]
# family = "InconsolataLGC Nerd Font"
# style = "Medium"
# 
# [fonts.inconsolata.offset]
# y = 3
# 
# [fonts.inconsolata-dz]
# size = 12.0

#[fonts.inconsolata-dz."<<"]
#size = 12.0
#use_thin_strokes = true
#
#[fonts.inconsolata-dz."<<".glyph_offset]
#x = 0
#y = 0
#
#[fonts.inconsolata-dz."<<".offset]
#x = 0
#y = 0

# [fonts.inconsolata-dz.normal]
# family = "Inconsolata-dz for Powerline"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3H"
key = "Home"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Home"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[H"
key = "Home"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1;3F"
key = "End"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "End"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[F"
key = "End"
mode = "~AppCursor"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[5;2~"
key = "PageUp"
mode = "Alt"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[5;5~"
key = "PageUp"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[5;3~"
key = "PageUp"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[5~"
key = "PageUp"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[6;2~"
key = "PageDown"
mode = "Alt"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[6;5~"
key = "PageDown"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[6;3~"
key = "PageDown"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[6~"
key = "PageDown"

[[keyboard.bindings]]
chars = "\u001B[Z"
key = "Tab"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u007F"
key = "Back"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[2~"
key = "Insert"

[[keyboard.bindings]]
chars = "\u001B[3~"
key = "Delete"

[[keyboard.bindings]]
chars = "\u001B[1;2D"
key = "Left"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5D"
key = "Left"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3D"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[D"
key = "Left"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOD"
key = "Left"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1;2C"
key = "Right"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5C"
key = "Right"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3C"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[C"
key = "Right"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOC"
key = "Right"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1;2A"
key = "Up"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5A"
key = "Up"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3A"
key = "Up"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[A"
key = "Up"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOA"
key = "Up"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1;2B"
key = "Down"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5B"
key = "Down"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3B"
key = "Down"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[B"
key = "Down"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOB"
key = "Down"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001BOP"
key = "F1"

[[keyboard.bindings]]
chars = "\u001BOQ"
key = "F2"

[[keyboard.bindings]]
chars = "\u001BOR"
key = "F3"

[[keyboard.bindings]]
chars = "\u001BOS"
key = "F4"

[[keyboard.bindings]]
chars = "\u001B[15~"
key = "F5"

[[keyboard.bindings]]
chars = "\u001B[17~"
key = "F6"

[[keyboard.bindings]]
chars = "\u001B[18~"
key = "F7"

[[keyboard.bindings]]
chars = "\u001B[19~"
key = "F8"

[[keyboard.bindings]]
chars = "\u001B[20~"
key = "F9"

[[keyboard.bindings]]
chars = "\u001B[21~"
key = "F10"

[[keyboard.bindings]]
chars = "\u001B[23~"
key = "F11"

[[keyboard.bindings]]
chars = "\u001B[24~"
key = "F12"

[[keyboard.bindings]]
chars = "\u001B[1;2P"
key = "F1"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;2Q"
key = "F2"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;2R"
key = "F3"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;2S"
key = "F4"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[15;2~"
key = "F5"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[17;2~"
key = "F6"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[18;2~"
key = "F7"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[19;2~"
key = "F8"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[20;2~"
key = "F9"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[21;2~"
key = "F10"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[23;2~"
key = "F11"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[24;2~"
key = "F12"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5P"
key = "F1"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;5Q"
key = "F2"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;5R"
key = "F3"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;5S"
key = "F4"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[15;5~"
key = "F5"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[17;5~"
key = "F6"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[18;5~"
key = "F7"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[19;5~"
key = "F8"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[20;5~"
key = "F9"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[21;5~"
key = "F10"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[23;5~"
key = "F11"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[24;5~"
key = "F12"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;6P"
key = "F1"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;6Q"
key = "F2"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;6R"
key = "F3"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;6S"
key = "F4"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[15;6~"
key = "F5"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[17;6~"
key = "F6"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[18;6~"
key = "F7"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[19;6~"
key = "F8"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[20;6~"
key = "F9"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[21;6~"
key = "F10"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[23;6~"
key = "F11"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[24;6~"
key = "F12"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;3P"
key = "F1"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[1;3Q"
key = "F2"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[1;3R"
key = "F3"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[1;3S"
key = "F4"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[15;3~"
key = "F5"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[17;3~"
key = "F6"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[18;3~"
key = "F7"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[19;3~"
key = "F8"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[20;3~"
key = "F9"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[21;3~"
key = "F10"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[23;3~"
key = "F11"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[24;3~"
key = "F12"
mods = "Super"

[[keyboard.bindings]]
chars = """

"""
key = "NumpadEnter"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Command"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
key = "Comma"
mods = "Command"

[keyboard.bindings.command]
args = ["-a", "MacVim", "~/.config/alacritty/alacritty.toml"]
program = "open"

[[keyboard.bindings]]
chars = "\u001Ba"
key = "A"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bc"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Be"
key = "E"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bg"
key = "G"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bi"
key = "I"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bm"
key = "M"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bn"
key = "N"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bo"
key = "O"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bp"
key = "P"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bq"
key = "Q"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Br"
key = "R"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bs"
key = "S"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bt"
key = "T"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bu"
key = "U"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bv"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bw"
key = "W"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bx"
key = "X"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001By"
key = "Y"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bz"
key = "Z"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BA"
key = "A"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BB"
key = "B"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BC"
key = "C"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BD"
key = "D"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BE"
key = "E"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BF"
key = "F"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BG"
key = "G"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BH"
key = "H"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BI"
key = "I"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BJ"
key = "J"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BK"
key = "K"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BL"
key = "L"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BM"
key = "M"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BN"
key = "N"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BO"
key = "O"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BP"
key = "P"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BQ"
key = "Q"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BR"
key = "R"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BS"
key = "S"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BT"
key = "T"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BU"
key = "U"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BV"
key = "V"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BW"
key = "W"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BX"
key = "X"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BY"
key = "Y"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BZ"
key = "Z"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B1"
key = "Key1"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B2"
key = "Key2"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B3"
key = "Key3"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B4"
key = "Key4"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B5"
key = "Key5"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B6"
key = "Key6"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B7"
key = "Key7"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B8"
key = "Key8"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B9"
key = "Key9"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B0"
key = "Key0"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001E"
key = "Key6"
mods = "Control"

#[[keyboard.bindings]]
#chars = "\u001B`"
#key = "Grave"
#mods = "Alt"
#
#[[keyboard.bindings]]
#chars = "\u001B~"
#key = "Grave"
#mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B."
key = "Period"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B*"
key = "Key8"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B#"
key = "Key3"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B>"
key = "Period"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B<"
key = "Comma"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B_"
key = "Minus"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B%"
key = "Key5"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B^"
key = "Key6"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B\\"
key = "Backslash"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B|"
key = "Backslash"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B/"
key = "Slash"
mods = "Alt"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

#[mouse.double_click]
#threshold = 300

#[mouse.triple_click]
#threshold = 300

# [schemes.base16-dark.bright]
# black = "0x585858"
# blue = "0x7cafc2"
# cyan = "0x86c1b9"
# green = "0xa1b56c"
# magenta = "0xba8baf"
# red = "0xab4642"
# white = "0xf8f8f8"
# yellow = "0xf7ca88"
# 
# [schemes.base16-dark.cursor]
# cursor = "0xd8d8d8"
# text = "0xd8d8d8"
# 
# [schemes.base16-dark.normal]
# black = "0x181818"
# blue = "0x7cafc2"
# cyan = "0x86c1b9"
# green = "0xa1b56c"
# magenta = "0xba8baf"
# red = "0xab4642"
# white = "0xd8d8d8"
# yellow = "0xf7ca88"
# 
# [schemes.base16-dark.primary]
# background = "0x181818"
# foreground = "0xd8d8d8"
# 
# [schemes.base16-solarized-dark.bright]
# black = "0x657b83"
# blue = "0x268bd2"
# cyan = "0x2aa198"
# green = "0x859900"
# magenta = "0x6c71c4"
# red = "0xdc322f"
# white = "0x93a1a1"
# yellow = "0xb58900"
# 
# [schemes.base16-solarized-dark.cursor]
# cursor = "0x93a1a1"
# text = "0x002b36"
# 
# [schemes.base16-solarized-dark.normal]
# black = "0x002b36"
# blue = "0x268bd2"
# cyan = "0x2aa198"
# green = "0x859900"
# magenta = "0x6c71c4"
# red = "0xdc322f"
# white = "0x93a1a1"
# yellow = "0xb58900"
# 
# [schemes.base16-solarized-dark.primary]
# background = "0x002b36"
# foreground = "0x93a1a1"
# 
# [schemes.gruvbox-dark.bright]
# black = "0x928374"
# blue = "0x83a598"
# cyan = "0x8ec07c"
# green = "0xb8bb26"
# magenta = "0xd3869b"
# red = "0xfb4934"
# white = "0xebdbb2"
# yellow = "0xfabd2f"
# 
# [schemes.gruvbox-dark.normal]
# black = "0x282828"
# blue = "0x458588"
# cyan = "0x689d6a"
# green = "0x98971a"
# magenta = "0xb16286"
# red = "0xcc241d"
# white = "0xa89984"
# yellow = "0xd79921"
# 
# [schemes.gruvbox-dark.primary]
# background = "0x282828"
# foreground = "0xebdbb2"
# 
# [schemes.tomorrow-night.bright]
# black = "0x666666"
# blue = "0x81a2be"
# cyan = "0x54ced6"
# green = "0x9ec400"
# magenta = "0xb77ee0"
# red = "0xff3334"
# white = "0x282a2e"
# yellow = "0xf0c674"
# 
# [schemes.tomorrow-night.cursor]
# cursor = "0xffffff"
# text = "0x1d1f21"
# 
# [schemes.tomorrow-night.normal]
# black = "0x1d1f21"
# blue = "0x81a2be"
# cyan = "0x70c0ba"
# green = "0xb5bd68"
# magenta = "0xb294bb"
# red = "0xcc6666"
# white = "0x373b41"
# yellow = "0xe6c547"
# 
# [schemes.tomorrow-night.primary]
# background = "0x1d1f21"
# foreground = "0xc5c8c6"
# 
# [schemes.tomorrow-night-bright.bright]
# black = "0x666666"
# blue = "0x7aa6da"
# cyan = "0x54ced6"
# green = "0x9ec400"
# magenta = "0xb77ee0"
# red = "0xff3334"
# white = "0xffffff"
# yellow = "0xe7c547"
# 
# [schemes.tomorrow-night-bright.normal]
# black = "0x000000"
# blue = "0x7aa6da"
# cyan = "0x70c0ba"
# green = "0xb9ca4a"
# magenta = "0xc397d8"
# red = "0xd54e53"
# white = "0xeaeaea"
# yellow = "0xe6c547"
# 
# [schemes.tomorrow-night-bright.primary]
# background = "0x000000"
# foreground = "0xeaeaea"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
startup_mode = "Windowed"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 6
y = 0
